name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
    - master  # Mude para a branch que você deseja realizar o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build -- --prod --base-href /anota-ai/

    - name: Deploy to GitHub Pages
      run: npx angular-cli-ghpages --dir=dist/<nome-do-projeto> --base-href=/anota-ai/
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
